// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdHWShbgKeqyp97ccg0KUBAvPVeMHjQoU',
    appId: '1:156909394511:web:1e525ce64a191d51b7683a',
    messagingSenderId: '156909394511',
    projectId: 'chat-app-24d0d',
    authDomain: 'chat-app-24d0d.firebaseapp.com',
    storageBucket: 'chat-app-24d0d.appspot.com',
    measurementId: 'G-VC1BY086DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_6KDr2XN0kBtCfvVdNzvQAzjZHi57wM8',
    appId: '1:156909394511:android:fa0a7b3c687b51aeb7683a',
    messagingSenderId: '156909394511',
    projectId: 'chat-app-24d0d',
    storageBucket: 'chat-app-24d0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2vy428UIRKNiRDrOfq3hNHojdz8-cuMU',
    appId: '1:156909394511:ios:d9ef8838a2071ab7b7683a',
    messagingSenderId: '156909394511',
    projectId: 'chat-app-24d0d',
    storageBucket: 'chat-app-24d0d.appspot.com',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2vy428UIRKNiRDrOfq3hNHojdz8-cuMU',
    appId: '1:156909394511:ios:9d127a93d2804e1eb7683a',
    messagingSenderId: '156909394511',
    projectId: 'chat-app-24d0d',
    storageBucket: 'chat-app-24d0d.appspot.com',
    iosBundleId: 'com.example.chattApp.RunnerTests',
  );
}
